### ISSUE TITLE
Validator crashes (0.14 CLI - PKG-1)

### ISSUE THREAD

**Issue by maria-messerschmidt** [openpreserve/odf-validator#192]
When validating a PDF document renamed as .ods, I expect the validator to report PKG-1 and POL_2 when running with profile and DOC-1 (or possibly PKG-1) when running without profile.

Currently, the validator crashes and outputs the following:

APP-1: [INFO] Validating C:\Users\maria\Desktop\014test\AT002.ods.
APP-4: [INFO] Validation report for C:\Users\maria\Desktop\014test\AT002.ods.
DOC-1: [ERROR] C:\Users\maria\Desktop\014test\AT002.ods An OpenDocument document SHALL be a single XML file or a Zip file.
NOT VALID, 1 errors, 0 warnings and 0 info messages.

java.lang.NullPointerException: Cannot invoke "org.openpreservation.odf.document.OpenDocument.getPackage()" because "report.document" is null
        at org.openpreservation.odf.validation.rules.ProfileImpl.check(ProfileImpl.java:49)
        at org.openpreservation.odf.apps.CliValidator.profileReport(CliValidator.java:87)
        at org.openpreservation.odf.apps.CliValidator.call(CliValidator.java:58)
        at org.openpreservation.odf.apps.CliValidator.call(CliValidator.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.openpreservation.odf.apps.CliValidator.main(CliValidator.java:98)

[AT002.ods](https://github.com/user-attachments/files/17210151/AT002.ods)

It looks like this is accurate without the profile, but then crashes when attempting to validate with the profile.

**Comment by maria-messerschmidt** [comment]
@carlwilson This issue is still happening in 0.16 on the same file.

C:\odf\odf-validator-0.16.0>odf-validator.bat -p D:\odsfiler\AT002.ods
APP-1: [INFO] Validating D:\odsfiler\AT002.ods.
APP-4: [INFO] Validation report for D:\odsfiler\AT002.ods.
DOC-1: [ERROR] D:\odsfiler\AT002.ods An OpenDocument document SHALL be a single XML file or a Zip file.
java.lang.NullPointerException: Cannot invoke "org.openpreservation.odf.document.OpenDocument.isPackage()" because "report.document" is null
        at org.openpreservation.odf.apps.CliValidator.isEncrypted(CliValidator.java:133)
        at org.openpreservation.odf.apps.CliValidator.results(CliValidator.java:128)
        at org.openpreservation.odf.apps.CliValidator.call(CliValidator.java:56)
        at org.openpreservation.odf.apps.CliValidator.call(CliValidator.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.openpreservation.odf.apps.CliValidator.main(CliValidator.java:98)

**Comment by carlwilson** [comment]
Ahhh, sorry fixed and reintroduced (the stack trace has changed), on a fix now.

**Comment by carlwilson** [comment]
A fix is attached here https://github.com/openpreserve/odf-validator/releases/tag/v0.16.1

**Comment by maria-messerschmidt** [comment]
Confirmed as fixed with 0.16.1
